jupyterhub:
  hub:
    baseUrl: /bootcamp-hub/
    annotations:
      prometheus.io/scrape: "true"
      # this needs to start with the value of `hub.baseUrl`
      prometheus.io/path: /bootcamp-hub/hub/metrics
#    extraConfig:
#      auth: |
#        c.JupyterHub.authenticator_class = 'hashauthenticator.HashAuthenticator'
#      admin: |
#        c.Authenticator.admin_users = {'lwasser', 'jlpalomino ', 'betatim'}
#        c.JupyterHub.admin_access = True
  singleuser:
    image:
      # tag will be set by travis on deployment
      name: earthlabhubops/ea-k8s-user-bootcamp-hub
      tag: set-on-deployment
    startTimeout: 600
    cpu:
      guarantee: 1.
      limit: 2.
    memory:
      guarantee: 1G
      limit: 2G
    lifecycleHooks:
      postStart:
        exec:
          command:
            - "sh"
            - "-c"
            - >
              gitpuller https://github.com/earthlab-education/ea-bootcamp-day-1 master notebooks;
  proxy:
    service:
      type: ClusterIP
  ingress:
    enabled: true
    hosts:
      - hub.earthdatascience.org
    annotations:
      ingress.kubernetes.io/proxy-body-size: 64m
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    tls:
      - secretName: kubelego-tls-jupyterhub
        hosts:
          - hub.earthdatascience.org
  auth:
    whitelist:
      users:
        - earth.lab
        - jenp0277
    type: github
    github:
      callbackUrl: "https://hub.earthdatascience.org/bootcamp-hub/hub/oauth_callback"
      org_whitelist:
        - "earthlab-education"
    scopes:
      - "read:user"
