jupyterhub:
  hub:
    baseUrl: /wshub/
    annotations:
      prometheus.io/scrape: "true"
      # this needs to start with the value of `hub.baseUrl`
      prometheus.io/path: /wshub/hub/metrics
    extraConfig:
      auth: |
        c.JupyterHub.authenticator_class = 'hashauthenticator.HashAuthenticator'
      admin: |
        c.Authenticator.admin_users = {'leah-admin', 'tim-admin'}
        c.JupyterHub.admin_access = True
    image:
      # tag will be set by travis on deployment
      name: earthlabhubops/ea-k8s-hub-wshub
      tag: set-on-deployment
  singleuser:
    image:
      # tag will be set by travis on deployment
      name: earthlabhubops/ea-k8s-user-wshub
      tag: set-on-deployment
    startTimeout: 600
    cpu:
      guarantee: 1.
      limit: 2.
    memory:
      guarantee: 1G
      limit: 2G
    lifecycleHooks:
      postStart:
        exec:
          command:
            - "sh"
            - "-c"
            - >
              rsync --ignore-existing -razv --progress /data/ /home/jovyan/earth-analytics/data;
              gitpuller https://github.com/earthlab-education/2018-07-20-spatial-python-workshop master materials;
  proxy:
    service:
      type: ClusterIP
  ingress:
    enabled: true
    hosts:
      - hub.earthdatascience.org
    annotations:
      ingress.kubernetes.io/proxy-body-size: 64m
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    tls:
      - secretName: kubelego-tls-jupyterhub
        hosts:
          - hub.earthdatascience.org
