dependencies:
- name: nginx-ingress
  version: 0.20.1
  repository: https://kubernetes-charts.storage.googleapis.com
- name: kube-lego
  version: 0.4.2
  repository: https://kubernetes-charts.storage.googleapis.com
