prometheus:
  nodeExporter:
    updateStrategy:
      type: RollingUpdate
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  rbac:
    create: true
  server:
    ingress:
      enabled: true
      hosts:
        - prometheus.hub.earthdatascience.org
      tls:
        - secretName: kubelego-tls-prometheus
          hosts:
            - prometheus.hub.earthdatascience.org
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: 500m
        memory: 1Gi
    persistentVolume:
      size: 20Gi
    retention: 30d

grafana:
  ingress:
    hosts:
      - grafana.hub.earthdatascience.org
    tls:
      - hosts:
          - grafana.hub.earthdatascience.org
        secretName: kubelego-tls-grafana
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  grafana.ini:
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Viewer
    auth.basic:
      enabled: true

  resources:
    requests:
      cpu: "0.2"
      memory: 256Mi
    limits:
      cpu: "0.2"
      memory: 256Mi
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: prometheus
          orgId: 1
          type: prometheus
          url: https://prometheus.hub.earthdatascience.org
          access: direct
          isDefault: true
          editable: false
