jupyterhub:
  hub:
    baseUrl: /staginghub
  proxy:
    service:
      type: ClusterIP
  ingress:
    enabled: true
    hosts:
      - hub.earthdatascience.org
    annotations:
      ingress.kubernetes.io/proxy-body-size: 64m
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    tls:
      - secretName: kubelego-tls-jupyterhub
        hosts:
          - hub.earthdatascience.org

  auth:
    type: github
    github:
      callbackUrl: "https://hub.earthdatascience.org/staginghub/hub/oauth_callback"
      org_whitelist:
        - "earthlab"
    scopes:
      - "read:user"
