jupyterhub:
  hub:
    baseUrl: /staginghub/
    annotations:
      prometheus.io/scrape: "true"
      # this needs to start with the value of `hub.baseUrl`
      prometheus.io/path: /staginghub/hub/metrics
  singleuser:
    cpu:
      guarantee: 0.1
      limit: 1.
    memory:
      guarantee: 500M
      limit: 500M
  proxy:
    service:
      type: ClusterIP
  ingress:
    enabled: true
    hosts:
      - hub.earthdatascience.org
    annotations:
      ingress.kubernetes.io/proxy-body-size: 64m
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    tls:
      - secretName: kubelego-tls-jupyterhub
        hosts:
          - hub.earthdatascience.org

  auth:
    type: google
    google:
      callbackUrl: "https://hub.earthdatascience.org/staginghub/hub/oauth_callback"
      hostedDomain: "colorado.edu"
      loginService: "Colorado University"
