jupyterhub:
  hub:
    baseUrl: /earthhub/
    annotations:
      prometheus.io/scrape: "true"
      # this needs to start with the value of `hub.baseUrl`
      prometheus.io/path: /earthhub/hub/metrics
  singleuser:
    image:
      # tag will be set by travis on deployment
      name: earthlabhubops/ea-k8s-user-earthhub
  proxy:
    service:
      type: ClusterIP
  ingress:
    enabled: true
    hosts:
      - hub.earthdatascience.org
    annotations:
      ingress.kubernetes.io/proxy-body-size: 64m
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    tls:
      - secretName: kubelego-tls-jupyterhub
        hosts:
          - hub.earthdatascience.org

  auth:
    type: google
    google:
      callbackUrl: "https://hub.earthdatascience.org/earthhub/hub/oauth_callback"
      hostedDomain: "colorado.edu"
      loginService: "Colorado University"
